on:
  - push
  - pull_request

name: Main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/checkout@v2
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0
      - uses: ./
        id: dunamai
        with:
          install: '1.13.2'
          env-var: MY_VERSION
          command: dunamai from git
          args: --style pep440
      - if: matrix.os != 'windows-latest'
        run: echo $MY_VERSION from environment variable
      - if: matrix.os == 'windows-latest'
        run: echo $env:MY_VERSION from environment variable
      - run: echo ${{ steps.dunamai.outputs.version }} from outputs
